### ISSUE TITLE
REGION_SEPARATOR logic fails when run under POSIX shell

### ISSUE THREAD

**Issue by dougbarth** [qoomon/aws-ssm-ssh-proxy-command#24]
The various shell scripts use a Bash-specific construct, which fails when running the script somewhere where `sh` is a POSIX shell (e.g. GitHub Actions).

https://github.com/qoomon/aws-ssm-ssh-proxy-command/blob/6ab35e48c5786b8d0da6084f7c0cc0fb5b86c7c3/ec2-instance-connect/aws-ssm-ssh-proxy-command.sh#L15-L20

Running all scripts through [`shellcheck`](https://www.shellcheck.net/), flags this and other issues:

`find . -name '*.sh' | xargs shellcheck`

```
In ./aws-ssm-ssh-proxy-command.sh line 16:
if [[ "${instance_id}" == *"${REGION_SEPARATOR}"* ]]
   ^-- SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In ./aws-ssm-ssh-proxy-command.sh line 18:
  export AWS_DEFAULT_REGION="${instance_id##*${REGION_SEPARATOR}}"
                                             ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  export AWS_DEFAULT_REGION="${instance_id##*"${REGION_SEPARATOR}"}"


In ./aws-ssm-ssh-proxy-command.sh line 19:
  instance_id="${instance_id%%${REGION_SEPARATOR}*}"
                              ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  instance_id="${instance_id%%"${REGION_SEPARATOR}"*}"


In ./ec2-instance-connect/aws-ssm-ssh-proxy-command.sh line 16:
if [[ "${instance_id}" == *"${REGION_SEPARATOR}"* ]]
   ^-- SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In ./ec2-instance-connect/aws-ssm-ssh-proxy-command.sh line 18:
  export AWS_DEFAULT_REGION="${instance_id##*${REGION_SEPARATOR}}"
                                             ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  export AWS_DEFAULT_REGION="${instance_id##*"${REGION_SEPARATOR}"}"


In ./ec2-instance-connect/aws-ssm-ssh-proxy-command.sh line 19:
  instance_id="${instance_id%%${REGION_SEPARATOR}*}"
                              ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  instance_id="${instance_id%%"${REGION_SEPARATOR}"*}"


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 7:
if [[ "${instance_id}" == *"${REGION_SEPARATOR}"* ]]
   ^-- SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 9:
  export AWS_DEFAULT_REGION="${instance_id##*${REGION_SEPARATOR}}"
                                             ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  export AWS_DEFAULT_REGION="${instance_id##*"${REGION_SEPARATOR}"}"


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 10:
  instance_id="${instance_id%%${REGION_SEPARATOR}*}"
                              ^-----------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
  instance_id="${instance_id%%"${REGION_SEPARATOR}"*}"


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 15:
STATUS=`aws ssm describe-instance-information --filters Key=InstanceIds,Values=${instance_id} --output text --query 'InstanceInformationList[0].PingStatus'`
       ^-- SC2006 (style): Use $(...) notation instead of legacy backticks `...`.
                                                                               ^------------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
STATUS=$(aws ssm describe-instance-information --filters Key=InstanceIds,Values="${instance_id}" --output text --query 'InstanceInformationList[0].PingStatus')


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 16:
if [ $STATUS != 'Online' ]
     ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
if [ "$STATUS" != 'Online' ]


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 21:
  while [ $(( $(date +%s) - $START_INSTANCE_START)) -le ${START_INSTANCE_TIMEOUT} ]
                            ^-------------------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 23:
      >/dev/stderr echo -n "."
                        ^-- SC3037 (warning): In POSIX sh, echo flags are undefined.


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 25:
      STATUS=`aws ssm describe-instance-information --filters Key=InstanceIds,Values=${instance_id} --output text --query 'InstanceInformationList[0].PingStatus'`
             ^-- SC2006 (style): Use $(...) notation instead of legacy backticks `...`.
                                                                                     ^------------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
      STATUS=$(aws ssm describe-instance-information --filters Key=InstanceIds,Values="${instance_id}" --output text --query 'InstanceInformationList[0].PingStatus')


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 26:
      if [ ${STATUS} == 'Online' ]
           ^-------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                     ^-- SC3014 (warning): In POSIX sh, == in place of = is undefined.

Did you mean: 
      if [ "${STATUS}" == 'Online' ]


In ./aws-ssm-ssh-proxy-command_start-ec2-instance.sh line 33:
  if [ $STATUS != 'Online' ]
       ^-----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
  if [ "$STATUS" != 'Online' ]

For more information:
  https://www.shellcheck.net/wiki/SC3010 -- In POSIX sh, [[ ]] is undefined.
  https://www.shellcheck.net/wiki/SC3014 -- In POSIX sh, == in place of = is ...
  https://www.shellcheck.net/wiki/SC3037 -- In POSIX sh, echo flags are undef...

```

**Comment by qoomon** [comment]
Should be fixed see main branch

**Comment by JamesDunne** [comment]
Running on MacOS with zsh it seems this separator logic is still failing.

**Comment by qoomon** [comment]
close again in favour of https://github.com/qoomon/aws-ssm-ssh-proxy-command/issues/26
